/**
 * Treasure config contract.
 *
 * Follows TreasureRow.test.jsx's idiom: vitest + react-dom/server, no jsdom,
 * no simulated clicks — this repo's test suite has neither jsdom/happy-dom
 * nor @testing-library installed (checked: not in package.json, not in
 * node_modules), so every existing test here is a static render or a pure
 * function call, never a mounted, interactive DOM.
 *
 * TreasureConfig.jsx is split the same way MoveBlipModal.jsx is: the actual
 * rules — what counts as dirty, what a PUT carries, how a failed fetch
 * becomes a message — live in plain exported functions, and the hooks-free
 * `ConfigView` renders any phase (loading / error / loaded) straight from
 * props. So "click Save" becomes "call saveConfig with the patch a click
 * would have built", and "the button reads disabled" becomes "render
 * ConfigView with dirty=false and check the markup" — the same substitution
 * MoveBlipModal's own tests make for refusal()/payload()/advice().
 */
import { beforeEach, describe, expect, it, vi } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
import React from "react";

import {
  ConfigView, draftFromConfig, isDirty, buildPatch, loadConfig, saveConfig,
} from "./TreasureConfig.jsx";

const CONFIG = {
  default_agent_notes: "Read the summary before editing anything.",
  default_header_html: '<div class="banner">FlightDeck</div>',
  default_footer_html: "<footer>generated by FlightDeck</footer>",
  updated_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
};

const fakeResponse = (status, body) => ({
  ok: status >= 200 && status < 300,
  status,
  json: async () => body,
});

beforeEach(() => {
  global.fetch = undefined;
});

describe("a successful load renders the three sections with the server's values", () => {
  it("shows all three labels and the loaded content", async () => {
    global.fetch = vi.fn().mockResolvedValue(fakeResponse(200, CONFIG));
    const config = await loadConfig();
    const draft = draftFromConfig(config);

    const html = renderToStaticMarkup(
      <ConfigView phase="loaded" draft={draft} dirty={false} saving={false}
                  saveError={null} updatedAt={config.updated_at}
                  onChange={() => {}} onSave={() => {}} />,
    );

    expect(html).toContain("Agent notes");
    expect(html).toContain("Header");
    expect(html).toContain("Footer");
    expect(html).toContain(CONFIG.default_agent_notes);
    // The header/footer values contain HTML tags, and a <textarea>'s content
    // is TEXT, not markup — React (correctly) HTML-escapes it, so the raw
    // string with real "<" / ">" never appears verbatim. Assert on the
    // escaped form instead of the literal value.
    expect(html).toContain("&lt;div class=&quot;banner&quot;&gt;FlightDeck&lt;/div&gt;");
    expect(html).toContain("&lt;footer&gt;generated by FlightDeck&lt;/footer&gt;");
  });
});

describe("Save is disabled until something is actually dirty", () => {
  it("stays disabled while the draft matches the baseline", () => {
    const draft = draftFromConfig(CONFIG);
    expect(isDirty(draft, CONFIG)).toBe(false);

    const html = renderToStaticMarkup(
      <ConfigView phase="loaded" draft={draft} dirty={false} saving={false}
                  saveError={null} updatedAt={null} onChange={() => {}} onSave={() => {}} />,
    );
    const save = html.match(/<button[^>]*>Save<\/button>/)[0];
    expect(save).toContain("disabled");
  });

  it("enables once one field changes", () => {
    const draft = { ...draftFromConfig(CONFIG), default_header_html: "<h1>new</h1>" };
    expect(isDirty(draft, CONFIG)).toBe(true);

    const html = renderToStaticMarkup(
      <ConfigView phase="loaded" draft={draft} dirty={true} saving={false}
                  saveError={null} updatedAt={null} onChange={() => {}} onSave={() => {}} />,
    );
    const save = html.match(/<button[^>]*>Save<\/button>/)[0];
    expect(save).not.toContain("disabled");
  });
});

describe("saving PUTs only the changed keys and adopts the response as the new baseline", () => {
  it("builds a patch limited to the changed keys", () => {
    const draft = { ...draftFromConfig(CONFIG), default_footer_html: "<footer>v2</footer>" };
    expect(buildPatch(draft, CONFIG)).toEqual({ default_footer_html: "<footer>v2</footer>" });
  });

  it("PUTs exactly that patch, and the response becomes the new baseline (Save goes disabled again)", async () => {
    const saved = { ...CONFIG, default_footer_html: "<footer>v2</footer>", updated_at: "2026-08-13T00:00:00Z" };
    global.fetch = vi.fn().mockResolvedValue(fakeResponse(200, saved));

    const patch = { default_footer_html: "<footer>v2</footer>" };
    const result = await saveConfig(patch);

    expect(global.fetch).toHaveBeenCalledWith("/api/treasure-config", expect.objectContaining({
      method: "PUT",
      body: JSON.stringify(patch),
    }));
    expect(result).toEqual(saved);

    // The server is the record: rebuilding baseline+draft from the response
    // (never from what was locally typed) is what puts Save back to disabled.
    const newDraft = draftFromConfig(result);
    expect(isDirty(newDraft, result)).toBe(false);
  });
});

describe("a failed load shows the error state with a retry, and retry re-fetches", () => {
  it("renders the error message and a retry control", () => {
    const html = renderToStaticMarkup(<ConfigView phase="error" error="500: Internal Server Error" onRetry={() => {}} />);
    expect(html).toContain("500: Internal Server Error");
    expect(html).toContain("Retry");
  });

  it("loadConfig throws on a failed response, and calling it again (what Retry does) reaches the network again", async () => {
    global.fetch = vi.fn()
      .mockResolvedValueOnce(fakeResponse(500, {}))
      .mockResolvedValueOnce(fakeResponse(200, CONFIG));

    await expect(loadConfig()).rejects.toThrow();
    const config = await loadConfig();

    expect(config).toEqual(CONFIG);
    expect(global.fetch).toHaveBeenCalledTimes(2);
  });
});

describe("a failed save surfaces the detail string", () => {
  it("throws the server's detail text rather than a generic status message", async () => {
    global.fetch = vi.fn().mockResolvedValue(
      fakeResponse(400, { detail: "default_header_html is too long" }),
    );
    await expect(saveConfig({ default_header_html: "x" }))
      .rejects.toThrow("default_header_html is too long");
  });

  it("renders that text next to Save", () => {
    const html = renderToStaticMarkup(
      <ConfigView phase="loaded" draft={draftFromConfig(CONFIG)} dirty={true} saving={false}
                  saveError="default_header_html is too long" updatedAt={null}
                  onChange={() => {}} onSave={() => {}} />,
    );
    expect(html).toContain("default_header_html is too long");
  });
});

describe("an empty value is a real value", () => {
  it("is saved as an empty string, not skipped and not sent as null", () => {
    const draft = { ...draftFromConfig(CONFIG), default_header_html: "" };
    const patch = buildPatch(draft, CONFIG);

    expect(Object.keys(patch)).toEqual(["default_header_html"]);
    expect(patch.default_header_html).toBe("");
    expect(patch.default_header_html).not.toBeNull();
  });

  it("saveConfig sends that empty string over the wire untouched", async () => {
    global.fetch = vi.fn().mockResolvedValue(fakeResponse(200, { ...CONFIG, default_header_html: "" }));
    await saveConfig({ default_header_html: "" });
    expect(global.fetch).toHaveBeenCalledWith("/api/treasure-config", expect.objectContaining({
      body: JSON.stringify({ default_header_html: "" }),
    }));
  });
});
