"""Missions store: schema + seed + service functions (the hold state-machine).

Pure SQLite, sqlite idiom (`?` placeholders) so the PostgreSQL adapter in db.py
can translate transparently. Reads take a short-lived connection; writes go
through the shared write connection under the runtime lock (see routers/missions.py).
The same tables are read/written by the standalone missions MCP process.
"""
import json
import random
import uuid
from datetime import datetime, timezone
from typing import List, Optional

from flightdeck import db

STATUSES = ("INBOX", "TODO", "IN_FLIGHT", "DONE")
# kind separates a NOTE (memory / reference an agent reads) from a TODO (task an
# agent acts on). Independent of status/column. Agents filter on it.
KINDS = ("NOTE", "TODO")


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _new_id() -> str:
    return "m_" + uuid.uuid4().hex[:8]


# Presence liveness: a hold is ACTIVE while its heartbeat is fresh, HELD when the
# session has gone quiet, STALE when it likely died without releasing.
ACTIVE_MAX_S = 90
HELD_MAX_S = 600


def _age_seconds(iso: Optional[str]):
    if not iso:
        return None
    try:
        t = datetime.strptime(iso, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
        return (datetime.now(timezone.utc) - t).total_seconds()
    except Exception:
        return None


def _hold_state(beat: Optional[str]) -> str:
    age = _age_seconds(beat)
    if age is None or age < ACTIVE_MAX_S:
        return "ACTIVE"
    if age < HELD_MAX_S:
        return "HELD"
    return "STALE"


# Friendly display identity for a hold (shown in the collaborator cursor/tooltip)
# instead of the raw session hash. A mythological name + an evocative word.
_NAMES = ["Daedalus", "Icarus", "Theseus", "Orion", "Atlas", "Perseus", "Hermes",
          "Odysseus", "Ariadne", "Persephone", "Helios", "Selene", "Prometheus",
          "Cassandra", "Nyx", "Calypso", "Hyperion", "Andromeda"]
_WORDS = ["Ember", "Quill", "Falcon", "Wildwood", "Cinder", "Harbor", "Vesper",
          "Marlow", "Thorn", "Sable", "Onyx", "Slate", "Wren", "Cove", "Flint", "Ashen"]


def random_name() -> str:
    return random.choice(_NAMES) + " " + random.choice(_WORDS)


def init(conn) -> None:
    """Create both tables (idempotent), then seed a handful of rows if empty.

    Engine-aware: the missions table is all-TEXT so its DDL is portable, but the
    mission_log surrogate key differs (SQLite AUTOINCREMENT vs PostgreSQL IDENTITY),
    and WAL is a SQLite-only PRAGMA. Mirrors db.py's _SCHEMA / _SCHEMA_PG split."""
    conn.execute("""
        CREATE TABLE IF NOT EXISTS missions (
          id TEXT PRIMARY KEY,
          status TEXT NOT NULL DEFAULT 'INBOX',
          title TEXT NOT NULL,
          note TEXT NOT NULL DEFAULT '',
          tags TEXT NOT NULL DEFAULT '[]',
          priority TEXT NOT NULL DEFAULT 'NORMAL',
          kind TEXT NOT NULL DEFAULT 'TODO',
          parent_id TEXT,
          hold_session TEXT,
          hold_name TEXT,
          hold_state TEXT,
          hold_since TEXT,
          hold_beat TEXT,
          is_read INTEGER NOT NULL DEFAULT 0,
          created_at TEXT NOT NULL,
          updated_at TEXT NOT NULL
        )""")
    if db.is_postgres():
        conn.execute("""
            CREATE TABLE IF NOT EXISTS mission_log (
              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              mission_id text NOT NULL,
              session_id text,
              action text NOT NULL,
              at text NOT NULL
            )""")
    else:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS mission_log (
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              mission_id TEXT NOT NULL,
              session_id TEXT,
              action TEXT NOT NULL,
              at TEXT NOT NULL
            )""")
        try:
            conn.execute("PRAGMA journal_mode=WAL")  # SQLite-only; lets the MCP process write too
        except Exception:
            pass
    _ensure_kind_column(conn)
    _ensure_hold_beat_column(conn)
    _ensure_hold_name_column(conn)
    _ensure_is_read_column(conn)
    _ensure_parent_id_column(conn)
    conn.commit()
    _seed_if_empty(conn)


def _ensure_parent_id_column(conn) -> None:
    """Migration: add parent_id (a child TODO links to its parent; NULL = top-level)."""
    if db.is_postgres():
        conn.execute("ALTER TABLE missions ADD COLUMN IF NOT EXISTS parent_id text")
    else:
        cols = {r[1] for r in conn.execute("PRAGMA table_info(missions)").fetchall()}
        if "parent_id" not in cols:
            conn.execute("ALTER TABLE missions ADD COLUMN parent_id TEXT")


def _ensure_is_read_column(conn) -> None:
    """Migration: add is_read (a DONE mission glows until opened, then dims)."""
    if db.is_postgres():
        conn.execute("ALTER TABLE missions ADD COLUMN IF NOT EXISTS is_read integer NOT NULL DEFAULT 0")
    else:
        cols = {r[1] for r in conn.execute("PRAGMA table_info(missions)").fetchall()}
        if "is_read" not in cols:
            conn.execute("ALTER TABLE missions ADD COLUMN is_read INTEGER NOT NULL DEFAULT 0")


def _ensure_kind_column(conn) -> None:
    """Migration: missions tables created before `kind` existed get it (default TODO)."""
    if db.is_postgres():
        conn.execute("ALTER TABLE missions ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'TODO'")
    else:
        cols = {r[1] for r in conn.execute("PRAGMA table_info(missions)").fetchall()}
        if "kind" not in cols:
            conn.execute("ALTER TABLE missions ADD COLUMN kind TEXT NOT NULL DEFAULT 'TODO'")


def _ensure_hold_beat_column(conn) -> None:
    """Migration: add hold_beat (heartbeat timestamp) to older missions tables."""
    if db.is_postgres():
        conn.execute("ALTER TABLE missions ADD COLUMN IF NOT EXISTS hold_beat text")
    else:
        cols = {r[1] for r in conn.execute("PRAGMA table_info(missions)").fetchall()}
        if "hold_beat" not in cols:
            conn.execute("ALTER TABLE missions ADD COLUMN hold_beat TEXT")


def _ensure_hold_name_column(conn) -> None:
    """Migration: add hold_name (friendly holder identity) to older missions tables."""
    if db.is_postgres():
        conn.execute("ALTER TABLE missions ADD COLUMN IF NOT EXISTS hold_name text")
    else:
        cols = {r[1] for r in conn.execute("PRAGMA table_info(missions)").fetchall()}
        if "hold_name" not in cols:
            conn.execute("ALTER TABLE missions ADD COLUMN hold_name TEXT")


def _log(conn, mission_id: str, session_id: Optional[str], action: str, at: Optional[str] = None) -> None:
    conn.execute(
        "INSERT INTO mission_log (mission_id, session_id, action, at) VALUES (?, ?, ?, ?)",
        (mission_id, session_id, action, at or _now()),
    )


def _row_to_mission(r, log: Optional[list] = None) -> dict:
    hold = None
    if r["hold_session"]:
        beat = r["hold_beat"] or r["hold_since"]
        age = _age_seconds(beat)
        hold = {"session_id": r["hold_session"], "name": r["hold_name"] or r["hold_session"],
                "state": _hold_state(beat), "since": r["hold_since"], "beat": beat,
                "beat_age": int(age) if age is not None else None}
    m = {
        "id": r["id"],
        "status": r["status"],
        "title": r["title"],
        "note": r["note"],
        "tags": json.loads(r["tags"] or "[]"),
        "priority": r["priority"],
        "kind": r["kind"],
        "parent_id": r["parent_id"],
        "is_read": bool(r["is_read"]),
        "hold": hold,
        "created_at": r["created_at"],
        "updated_at": r["updated_at"],
    }
    if log is not None:
        m["log"] = log
    return m


_STATUS_ORDER = "CASE status WHEN 'INBOX' THEN 0 WHEN 'TODO' THEN 1 " \
                "WHEN 'IN_FLIGHT' THEN 2 WHEN 'DONE' THEN 3 ELSE 4 END"


def list_missions(conn) -> dict:
    rows = conn.execute(
        "SELECT * FROM missions ORDER BY " + _STATUS_ORDER + ", updated_at DESC"
    ).fetchall()
    return {
        "missions": [_row_to_mission(r) for r in rows],
        "sessions": list_sessions(conn),
    }


def get_mission(conn, mid: str) -> Optional[dict]:
    r = conn.execute("SELECT * FROM missions WHERE id=?", (mid,)).fetchone()
    if not r:
        return None
    log_rows = conn.execute(
        "SELECT session_id, action, at FROM mission_log WHERE mission_id=? ORDER BY at DESC, id DESC",
        (mid,),
    ).fetchall()
    log = [{"session_id": lr["session_id"], "action": lr["action"], "at": lr["at"]} for lr in log_rows]
    m = _row_to_mission(r, log=log)
    child_rows = conn.execute(
        "SELECT * FROM missions WHERE parent_id=? ORDER BY " + _STATUS_ORDER + ", updated_at DESC", (mid,)
    ).fetchall()
    m["children"] = [_row_to_mission(c) for c in child_rows]
    return m


def list_sessions(conn) -> List[dict]:
    """Live holders, derived from missions (one hold per session in MVP)."""
    rows = conn.execute(
        "SELECT hold_session, hold_since, hold_beat, id FROM missions "
        "WHERE hold_session IS NOT NULL ORDER BY hold_since DESC"
    ).fetchall()
    return [{"session_id": r["hold_session"], "state": _hold_state(r["hold_beat"] or r["hold_since"]),
             "mission_id": r["id"], "since": r["hold_since"]} for r in rows]


def create_mission(conn, title: str, note: str = "", tags: Optional[list] = None,
                   priority: str = "NORMAL", status: str = "INBOX",
                   kind: str = "TODO", parent_id: Optional[str] = None,
                   claim_session: Optional[str] = None) -> dict:
    mid = _new_id()
    now = _now()
    status = status if status in STATUSES else "INBOX"
    kind = kind if kind in KINDS else "TODO"
    conn.execute(
        "INSERT INTO missions (id, status, title, note, tags, priority, kind, parent_id, "
        "hold_session, hold_name, hold_state, hold_since, hold_beat, is_read, created_at, updated_at) "
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (mid, status, title, note or "", json.dumps(tags or []), priority or "NORMAL", kind, parent_id,
         None, None, None, None, None, 0, now, now),
    )
    _log(conn, mid, None, "CREATED", now)
    conn.commit()
    if claim_session:
        return claim(conn, mid, claim_session)
    return get_mission(conn, mid)


def update_mission(conn, mid: str, **fields) -> Optional[dict]:
    allowed = {"status", "title", "note", "tags", "priority", "kind"}
    sets, vals = [], []
    for k, v in fields.items():
        if k not in allowed or v is None:
            continue
        if k == "tags":
            v = json.dumps(v)
        if k == "status" and v not in STATUSES:
            continue
        if k == "kind" and v not in KINDS:
            continue
        sets.append(k + "=?")
        vals.append(v)
    if not sets:
        return get_mission(conn, mid)
    if fields.get("status") == "DONE":
        sets.append("is_read=?")   # newly done -> unread (glows until opened)
        vals.append(0)
    sets.append("updated_at=?")
    vals.append(_now())
    vals.append(mid)
    cur = conn.execute("UPDATE missions SET " + ", ".join(sets) + " WHERE id=?", vals)
    conn.commit()
    if cur.rowcount == 0:
        return None
    # An edit by the holder is activity -> refresh the heartbeat so the card stays ACTIVE.
    conn.execute("UPDATE missions SET hold_beat=? WHERE id=? AND hold_session IS NOT NULL", (_now(), mid))
    conn.commit()
    return get_mission(conn, mid)


def mark_read(conn, mid: str) -> Optional[dict]:
    """Mark a mission read (opening a DONE one stops its glow, dims it)."""
    conn.execute("UPDATE missions SET is_read=1 WHERE id=?", (mid,))
    conn.commit()
    return get_mission(conn, mid)


def delete_mission(conn, mid: str) -> bool:
    """Delete a mission and its log. Returns True if a row was removed."""
    cur = conn.execute("DELETE FROM missions WHERE id=?", (mid,))
    conn.execute("DELETE FROM mission_log WHERE mission_id=?", (mid,))
    conn.execute("UPDATE missions SET parent_id=NULL WHERE parent_id=?", (mid,))  # orphan children, no dangling
    conn.commit()
    return (cur.rowcount or 0) > 0


def claim(conn, mid: str, session_id: str, name: Optional[str] = None) -> Optional[dict]:
    """Set an ACTIVE hold for session_id, with an optional friendly display name.
    Overwrites any existing hold (take-over)."""
    r = conn.execute("SELECT id FROM missions WHERE id=?", (mid,)).fetchone()
    if not r:
        return None
    now = _now()
    conn.execute(
        "UPDATE missions SET hold_session=?, hold_name=?, hold_state='ACTIVE', "
        "hold_since=?, hold_beat=?, updated_at=? WHERE id=?",
        (session_id, name or session_id, now, now, now, mid),
    )
    _log(conn, mid, session_id, "CLAIMED", now)
    conn.commit()
    return get_mission(conn, mid)


def release(conn, mid: str) -> Optional[dict]:
    r = conn.execute("SELECT hold_session FROM missions WHERE id=?", (mid,)).fetchone()
    if not r:
        return None
    now = _now()
    conn.execute(
        "UPDATE missions SET hold_session=NULL, hold_name=NULL, hold_state=NULL, "
        "hold_since=NULL, hold_beat=NULL, updated_at=? WHERE id=?",
        (now, mid),
    )
    _log(conn, mid, r["hold_session"], "RELEASED", now)
    conn.commit()
    return get_mission(conn, mid)


def land(conn, mid: str) -> Optional[dict]:
    r = conn.execute("SELECT hold_session FROM missions WHERE id=?", (mid,)).fetchone()
    if not r:
        return None
    now = _now()
    conn.execute(
        "UPDATE missions SET status='DONE', is_read=0, hold_session=NULL, hold_name=NULL, "
        "hold_state=NULL, hold_since=NULL, hold_beat=NULL, updated_at=? WHERE id=?",
        (now, mid),
    )
    _log(conn, mid, r["hold_session"], "LANDED", now)
    conn.commit()
    return get_mission(conn, mid)


# (status, title, note, tags, priority, hold_session, kind, hold_name)
_SEED = [
    ("IN_FLIGHT", "Re-confirm WVT facts ledger against source",
     "Header is >4h stale; verify the decided-vs-Deferred split against the resolved spec before the estimate.",
     ["CRM-EVENT", "HIGH"], "HIGH", "90FB37EE", "TODO", "Daedalus Ember"),
    ("IN_FLIGHT", "Build Discount Service PoC endpoints",
     "FastAPI at Deal, Quote, Invoice; clean-room, no Source A.", ["CRM-11198"], "NORMAL", "4F2B", "TODO", "Icarus Quill"),
    ("TODO", "Post CRM-11007 estimate comment",
     "Format ~Nd (1 DEV + AI Agent), CC Khang; split API and UI in hours.",
     ["CRM-11007", "HIGH"], "HIGH", "A1C4", "TODO", "Orion Slate"),
    ("TODO", "Refresh nakivo-graph blast radius",
     "Re-run ingest.py; confirm 68 transitive deps on nakivo_sale.", ["GRAPH"], "NORMAL", None, "TODO", None),
    ("INBOX", "Draft CRM-11372 helpdesk scope decision",
     "Scope still open per MEMORY; pick OSS vs dedicated for the pre-sale SE team.",
     ["HELPDESK", "CRM-11372"], "NORMAL", None, "TODO", None),
    ("INBOX", "Lago is AGPL section 13 (network use)",
     "Reference: network use triggers source obligations; it colours the reseller-facing portal decision.",
     ["BILLING", "MEMORY"], "NORMAL", None, "NOTE", None),
    ("INBOX", "Replies live as children of inline comments",
     "Reference: fetch replies via /rest/api/content/<id>/child/comment, not the v1 inline API.",
     ["CRM-EVENT", "MEMORY"], "NORMAL", None, "NOTE", None),
    ("DONE", "Run -u all migration on nakivo DB",
     "353 modules installed, 0 pending; sale_subscription subtree boots.", ["ODOO"], "NORMAL", None, "TODO", None),
]


def _seed_if_empty(conn) -> None:
    n = conn.execute("SELECT COUNT(*) AS c FROM missions").fetchone()
    if n and n["c"]:
        return
    now = _now()
    for status, title, note, tags, prio, hold, kind, hname in _SEED:
        mid = _new_id()
        conn.execute(
            "INSERT INTO missions (id, status, title, note, tags, priority, kind, "
            "hold_session, hold_name, hold_state, hold_since, hold_beat, is_read, created_at, updated_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (mid, status, title, note, json.dumps(tags), prio, kind,
             hold, hname, "ACTIVE" if hold else None, now if hold else None, now if hold else None,
             1 if status == "DONE" else 0, now, now),
        )
        _log(conn, mid, None, "CREATED", now)
        if hold:
            _log(conn, mid, hold, "CLAIMED", now)
    conn.commit()
