"""Deterministic Route Loom projection for a Claude Code session.

The raw transcript remains the source of truth.  This module streams that
JSONL once and builds a small, overview-friendly route:

    raw turns -> user clearances -> lane-classified waypoints -> compact route

No model call is involved, so the same session and waypoint budget always
produce the same projection.  Counts and turn ranges are retained for later
drill-down into the transcript.
"""

from __future__ import annotations

import argparse
from collections import Counter
from datetime import datetime
import hashlib
import json
import os
import re

from flightdeck import transcript


ROUTE_RULE_VERSION = "route-v1"
DEFAULT_MAX_WAYPOINTS = 24
MIN_WAYPOINTS = 4
MAX_WAYPOINTS = 64

LANES = (
    {"id": "brief", "label": "Brief", "description": "Human direction and decisions"},
    {"id": "research", "label": "Research", "description": "Read, search, inspect, and delegate"},
    {"id": "build", "label": "Build", "description": "Create or change artifacts"},
    {"id": "verify", "label": "Verify", "description": "Test, build, lint, and inspect output"},
    {"id": "operate", "label": "Operate", "description": "Git, deploy, containers, and external operations"},
    {"id": "recover", "label": "Recover", "description": "Error-heavy correction or retry work"},
)
_LANE_IDS = tuple(lane["id"] for lane in LANES)

# Text that looks like a user turn in Claude's JSONL but is generated by the
# runtime, a hook, or a local slash command.  It contributes to the current
# waypoint's telemetry but must never start a new clearance.
_NON_INSTRUCTION_PREFIX = re.compile(
    r"^(?:"
    r"<(?:local-command(?:-stdout|-stderr|-caveat)?|command-name|command-message|"
    r"command-args|command-stdout|command-stderr|system-reminder|task-notification|"
    r"task-id|user-prompt-submit-hook|ide_opened_file|ide_selection)\b|"
    r"<caution\b|caveat:|\[request interrupted|"
    r"this session is being continued from a previous conversation)",
    re.IGNORECASE,
)

_RESEARCH_TOOLS = {
    "read", "grep", "glob", "webfetch", "websearch", "toolsearch",
    "agent", "task", "workflow", "skill",
}
_BUILD_TOOLS = {"edit", "write", "notebookedit", "apply_patch", "artifact"}
_VERIFY_TOOL_FRAGMENTS = (
    "take_screenshot", "list_console", "snapshot", "browser", "playwright",
)
_VERIFY_COMMAND = re.compile(
    r"(?:^|[;&|\s])(?:pytest|npm\s+(?:test|run\s+(?:test|build|lint))|"
    r"pnpm\s+(?:test|build|lint)|yarn\s+(?:test|build|lint)|vitest|jest|"
    r"cargo\s+test|go\s+test|ruff|eslint|tsc|mypy|make\s+(?:test|check))\b",
    re.IGNORECASE,
)
_OPERATE_COMMAND = re.compile(
    # git mutations only; (?![\w-]) so `git merge-base` / `git rebase-todo`
    # (inspection) do NOT read as an operation.
    r"(?:^|[;&|\s])(?:git\s+(?:commit|push|pull|merge|rebase|tag)(?![\w-])|"
    r"docker(?:-compose|\s+compose)?\s+(?:up|down|restart|build|push)|"
    r"kubectl|helm|terraform|ansible|gh\s+pr\s+create|npm\s+publish)\b",
    re.IGNORECASE,
)
_RECOVERY_PROMPT = re.compile(
    r"\b(?:fix|retry|repair|broken|failed|failure|error|bug|regression|"
    r"sửa|lỗi|thử lại|không hoạt động|không đúng)\b", re.IGNORECASE)


def _clean_text(text: str, limit: int = 160) -> str:
    text = re.sub(r"\s+", " ", text or "").strip()
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "…"


def _instruction_text(turn: dict) -> str | None:
    """Return a real human instruction, excluding injected wrapper turns."""
    if turn.get("role") != "user" or turn.get("is_meta"):
        return None
    texts = [
        block.get("text", "").strip()
        for block in turn.get("blocks", [])
        if block.get("type") == "text" and not block.get("meta")
    ]
    text = " ".join(t for t in texts if t).strip()
    if not text or _NON_INSTRUCTION_PREFIX.match(text):
        return None
    return text


def _parse_ts(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except (TypeError, ValueError):
        return None


def _new_clearance(index: int, turn_no: int, turn: dict,
                   prompt: str | None = None) -> dict:
    prompt = prompt or "Session setup"
    uuid = turn.get("uuid") or f"turn-{turn_no}"
    return {
        "clearance_index": index,
        "clearance_ids": [uuid],
        "first_prompt": _clean_text(prompt),
        "last_prompt": _clean_text(prompt),
        "instruction_count": 0 if prompt == "Session setup" else 1,
        "start_turn": turn_no,
        "end_turn": turn_no,
        "first_ts": turn.get("ts"),
        "last_ts": turn.get("ts"),
        "turn_count": 0,
        "tool_count": 0,
        "error_count": 0,
        "subagent_count": 0,
        "tool_counts": Counter(),
        "lane_scores": Counter({"brief": 1}),
        "recovery_prompt": bool(_RECOVERY_PROMPT.search(prompt)),
    }


def _score_tool(clearance: dict, block: dict) -> None:
    name = (block.get("name") or "unknown").strip()
    lname = name.lower()
    clearance["tool_count"] += 1
    clearance["tool_counts"][name] += 1

    if lname in _RESEARCH_TOOLS or any(
            token in lname for token in ("search", "fetch", "read", "grep", "glob")):
        clearance["lane_scores"]["research"] += 3
    if lname in _BUILD_TOOLS or any(
            token in lname for token in ("edit", "write", "patch", "artifact")):
        clearance["lane_scores"]["build"] += 5
    if any(token in lname for token in _VERIFY_TOOL_FRAGMENTS):
        clearance["lane_scores"]["verify"] += 4
    if lname in {"agent", "task", "workflow"}:
        clearance["subagent_count"] += 1

    if lname in {"bash", "shell", "exec", "exec_command"}:
        raw_input = block.get("input") or {}
        command = ""
        if isinstance(raw_input, dict):
            command = str(raw_input.get("command") or raw_input.get("cmd") or "")
        if _VERIFY_COMMAND.search(command):
            clearance["lane_scores"]["verify"] += 6
        elif _OPERATE_COMMAND.search(command):
            clearance["lane_scores"]["operate"] += 6
        else:
            # Shell is weak evidence: most inspection commands are research.
            clearance["lane_scores"]["research"] += 1


def _choose_lane(clearance: dict) -> str:
    errors = clearance["error_count"]
    tools = clearance["tool_count"]
    scores = Counter(clearance["lane_scores"])
    if clearance["recovery_prompt"] and errors:
        scores["recover"] += 8
    if errors >= 3 and errors / max(tools, 1) >= 0.15:
        scores["recover"] += 7

    # On ties, prefer the more concrete execution lane over a generic brief or
    # research score.  Tuple order is deliberately stable.
    priority = {lane: i for i, lane in enumerate(_LANE_IDS)}
    return max(_LANE_IDS, key=lambda lane: (
        scores.get(lane, 0), priority[lane]))


def _finish_clearance(clearance: dict) -> dict:
    clearance["lane"] = _choose_lane(clearance)
    return clearance


def _gap_minutes(left: dict, right: dict) -> float:
    a, b = _parse_ts(left.get("last_ts")), _parse_ts(right.get("first_ts"))
    if not a or not b:
        return 0.0
    return max(0.0, (b - a).total_seconds() / 60)


def _merge_penalty(left: dict, right: dict) -> tuple:
    """Cost of hiding the boundary between two adjacent route groups.

    The lexicographic tuple makes the policy inspectable: same-lane boundaries
    disappear before cross-lane boundaries; anomalies and long idle gaps are
    retained as long as the requested node budget permits.
    """
    lane_change = int(left["lane"] != right["lane"])
    anomaly = int(bool(left["error_count"]) != bool(right["error_count"]))
    idle = int(_gap_minutes(left, right) >= 30)
    recovery = int(left["lane"] == "recover" or right["lane"] == "recover")
    combined_mass = left["turn_count"] + right["turn_count"]
    return (lane_change, recovery, anomaly, idle, combined_mass)


def _merge(left: dict, right: dict) -> dict:
    out = dict(left)
    out["clearance_ids"] = left["clearance_ids"] + right["clearance_ids"]
    if left["instruction_count"] == 0 and right["instruction_count"]:
        out["first_prompt"] = right["first_prompt"]
    out["last_prompt"] = right["last_prompt"]
    out["instruction_count"] = left["instruction_count"] + right["instruction_count"]
    out["end_turn"] = right["end_turn"]
    out["last_ts"] = right["last_ts"]
    for field in ("turn_count", "tool_count", "error_count", "subagent_count"):
        out[field] = left[field] + right[field]
    out["tool_counts"] = left["tool_counts"] + right["tool_counts"]
    out["lane_scores"] = left["lane_scores"] + right["lane_scores"]
    out["recovery_prompt"] = left["recovery_prompt"] or right["recovery_prompt"]
    out["lane"] = _choose_lane(out)
    return out


def _compact(clearances: list[dict], max_waypoints: int) -> list[dict]:
    groups = list(clearances)
    while len(groups) > max_waypoints:
        index = min(
            range(len(groups) - 1),
            key=lambda i: (_merge_penalty(groups[i], groups[i + 1]), i),
        )
        groups[index:index + 2] = [_merge(groups[index], groups[index + 1])]
    return groups


def _waypoint_id(group: dict) -> str:
    material = "\0".join(group["clearance_ids"]).encode("utf-8", "replace")
    return "wp-" + hashlib.sha1(material).hexdigest()[:10]


def _waypoint(group: dict, index: int) -> dict:
    instruction_count = group["instruction_count"]
    label = group["first_prompt"]
    if instruction_count > 1:
        label = _clean_text(f"{label} (+{instruction_count - 1} follow-ups)", 180)
    top_tools = [
        {"name": name, "count": count}
        for name, count in group["tool_counts"].most_common(4)
    ]
    return {
        "id": _waypoint_id(group),
        "sequence": index + 1,
        "lane": group["lane"],
        "label": label,
        "first_prompt": group["first_prompt"],
        "last_prompt": group["last_prompt"],
        "instruction_count": instruction_count,
        "start_turn": group["start_turn"],
        "end_turn": group["end_turn"],
        "turn_count": group["turn_count"],
        "tool_count": group["tool_count"],
        "error_count": group["error_count"],
        "subagent_count": group["subagent_count"],
        "first_ts": group["first_ts"],
        "last_ts": group["last_ts"],
        "top_tools": top_tools,
    }


def build_route(path: str, max_waypoints: int = DEFAULT_MAX_WAYPOINTS) -> dict:
    """Stream one session JSONL and return a compact Route Loom projection."""
    max_waypoints = max(MIN_WAYPOINTS, min(int(max_waypoints), MAX_WAYPOINTS))
    title = project = first_ts = last_ts = None
    title_priority = 0
    total_turns = total_tools = total_errors = 0
    clearances: list[dict] = []
    current = None

    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue

            typ = obj.get("type")
            if typ == "custom-title" and obj.get("customTitle"):
                title = obj["customTitle"]
                title_priority = 3
            elif typ == "ai-title" and obj.get("aiTitle") and title_priority < 2:
                title = obj["aiTitle"]
                title_priority = 2
            elif typ == "summary" and obj.get("summary") and title_priority < 1:
                title = obj["summary"]
                title_priority = 1
            if typ not in ("user", "assistant"):
                continue

            turn = transcript._norm_turn(obj)
            if turn is None:
                continue
            total_turns += 1
            project = project or obj.get("cwd")
            ts = turn.get("ts")
            if ts:
                first_ts = first_ts or ts
                last_ts = ts

            prompt = _instruction_text(turn)
            if prompt:
                if current is not None:
                    clearances.append(_finish_clearance(current))
                current = _new_clearance(len(clearances), total_turns, turn, prompt)
            elif current is None:
                current = _new_clearance(0, total_turns, turn)

            current["turn_count"] += 1
            current["end_turn"] = total_turns
            current["last_ts"] = ts or current["last_ts"]
            for block in turn.get("blocks", []):
                if block.get("type") == "tool_use":
                    _score_tool(current, block)
                    total_tools += 1
                elif block.get("type") == "tool_result" and block.get("is_error"):
                    current["error_count"] += 1
                    total_errors += 1

    if current is not None:
        clearances.append(_finish_clearance(current))

    groups = _compact(clearances, max_waypoints) if clearances else []
    waypoints = [_waypoint(group, i) for i, group in enumerate(groups)]
    lane_counts = Counter(wp["lane"] for wp in waypoints)
    return {
        "title": title,
        "project": project,
        "first_ts": first_ts,
        "last_ts": last_ts,
        "source": {
            "turn_count": total_turns,
            "instruction_count": sum(c["instruction_count"] for c in clearances),
            "clearance_count": sum(c["instruction_count"] for c in clearances),
            "atomic_segment_count": len(clearances),
            "tool_count": total_tools,
            "error_count": total_errors,
        },
        "projection": {
            "rule_version": ROUTE_RULE_VERSION,
            "max_waypoints": max_waypoints,
            "waypoint_count": len(waypoints),
            "compression_ratio": round(total_turns / max(len(waypoints), 1), 1),
            "lane_counts": dict(lane_counts),
        },
        "lanes": list(LANES),
        "waypoints": waypoints,
    }


def load_session_route(projects_dir: str, session_id: str,
                       max_waypoints: int = DEFAULT_MAX_WAYPOINTS) -> dict | None:
    path = transcript.find_session_file(projects_dir, session_id)
    if not path:
        return None
    data = build_route(path, max_waypoints=max_waypoints)
    data["session_id"] = session_id
    return data


# ---------------------------------------------------------------------------
# Clearance Route: one route PER user instruction.
#
# Where build_route() compresses a whole session into waypoints (each a merged
# clearance), a clearance route zooms into ONE instruction and lays out the
# turns it triggered as role-classified units: it starts at the human input
# and ends at the agent's closing summary.  Same deterministic spirit.
# ---------------------------------------------------------------------------

DEFAULT_MAX_UNITS = 9
MIN_UNITS = 3
MAX_UNITS = 20

# Role lanes for a single clearance (turn-level, not session-level).
CLEARANCE_LANES = (
    {"id": "lead", "label": "Lead", "description": "Human direction and agent framing"},
    {"id": "scout", "label": "Scout", "description": "Read, search, inspect, and delegate"},
    {"id": "builder", "label": "Builder", "description": "Create or change artifacts"},
    {"id": "reviewer", "label": "Reviewer", "description": "Test, lint, and inspect output"},
    {"id": "gate", "label": "Gate", "description": "Ship, operate, and hand off"},
)
_CLEARANCE_LANE_IDS = tuple(lane["id"] for lane in CLEARANCE_LANES)
# Which lane wins when a single turn touches several tool kinds.
_UNIT_LANE_PRIORITY = {"builder": 0, "reviewer": 1, "gate": 2, "scout": 3, "lead": 4}


def _tool_lane(name: str, command: str = "") -> str:
    lname = (name or "").lower()
    if lname in _BUILD_TOOLS or any(t in lname for t in ("edit", "write", "patch", "artifact")):
        return "builder"
    if any(t in lname for t in _VERIFY_TOOL_FRAGMENTS):
        return "reviewer"
    if lname in {"bash", "shell", "exec", "exec_command"}:
        if _VERIFY_COMMAND.search(command):
            return "reviewer"
        if _OPERATE_COMMAND.search(command):
            return "gate"
        return "scout"
    if lname in _RESEARCH_TOOLS or any(t in lname for t in ("search", "fetch", "read", "grep", "glob")):
        return "scout"
    return "scout"


def _block_command(block: dict) -> str:
    raw = block.get("input") or {}
    if isinstance(raw, dict):
        return str(raw.get("command") or raw.get("cmd") or "")
    return ""


def _block_target(block: dict) -> str | None:
    """A short human target for a tool call: file basename, command head, or host."""
    raw = block.get("input") or {}
    if not isinstance(raw, dict):
        return None
    path = raw.get("file_path") or raw.get("filePath") or raw.get("path")
    if path:
        return str(path).rstrip("/").split("/")[-1]
    command = raw.get("command") or raw.get("cmd")
    if command:
        # Drop a leading `cd <path> &&` / `cd <path>;`. Normalized tool inputs are
        # truncated upstream, so a command that is only a `cd <path>` prefix (the
        # rest cut off) yields no useful target - fall back to the tool name.
        command = re.sub(r"^\s*cd\s+\S+\s*(?:&&|;)?\s*", "", str(command)).strip()
        if command and not command.startswith("/"):
            return re.sub(r"\s+", " ", command).strip()[:40]
        return None
    url = raw.get("url")
    if url:
        m = re.search(r"https?://([^/]+)", str(url))
        return m.group(1) if m else str(url)[:40]
    if raw.get("pattern"):
        return f"/{str(raw['pattern'])[:30]}/"
    if raw.get("query"):
        return re.sub(r"\s+", " ", str(raw["query"])).strip()[:40]
    return None


def _turn_lane(turn: dict) -> str:
    """Dominant role lane of one turn."""
    if turn.get("role") == "user":
        return "lead"
    counts = Counter()
    for block in turn.get("blocks", []):
        if block.get("type") == "tool_use":
            counts[_tool_lane(block.get("name"), _block_command(block))] += 1
    if not counts:
        return "lead"  # text / thinking only -> framing or planning
    return max(counts, key=lambda lane: (counts[lane], -_UNIT_LANE_PRIORITY.get(lane, 9)))


def _first_text(turn: dict) -> str:
    for block in turn.get("blocks", []):
        if block.get("type") == "text" and not block.get("meta") and block.get("text", "").strip():
            return block["text"].strip()
    return ""


def _unit_label(unit: dict) -> str:
    lane = unit["lane"]
    if lane == "lead":
        return _clean_text(unit.get("lead_text") or "Planning", 90)
    if lane == "gate" and unit.get("is_summary"):
        return _clean_text(unit.get("lead_text") or "Handoff", 90)
    verb = {"scout": "Research", "builder": "Build", "reviewer": "Verify", "gate": "Operate"}[lane]
    target = unit.get("target")
    if not target and unit["tool_counts"]:
        target = unit["tool_counts"].most_common(1)[0][0]  # fall back to top tool name
    extra = unit["tool_count"] - 1
    if target and extra > 0:
        return _clean_text(f"{verb} · {target} +{extra}", 90)
    if target:
        return _clean_text(f"{verb} · {target}", 90)
    return f"{verb} · {unit['tool_count']} tool call{'s' if unit['tool_count'] != 1 else ''}"


def _new_unit(lane: str, turn_no: int, turn: dict) -> dict:
    return {
        "lane": lane,
        "start_turn": turn_no,
        "end_turn": turn_no,
        "turn_count": 0,
        "tool_count": 0,
        "error_count": 0,
        "subagent_count": 0,
        "tool_counts": Counter(),
        "target": None,
        "lead_text": None,
        "is_summary": False,
        "first_ts": turn.get("ts"),
        "last_ts": turn.get("ts"),
    }


def _absorb_turn(unit: dict, turn_no: int, turn: dict) -> None:
    unit["turn_count"] += 1
    unit["end_turn"] = turn_no
    unit["last_ts"] = turn.get("ts") or unit["last_ts"]
    for block in turn.get("blocks", []):
        btype = block.get("type")
        if btype == "tool_use":
            unit["tool_count"] += 1
            name = (block.get("name") or "tool").strip()
            unit["tool_counts"][name] += 1
            if name.lower() in {"agent", "task", "workflow"}:
                unit["subagent_count"] += 1
            if unit["target"] is None:
                unit["target"] = _block_target(block)
        elif btype == "tool_result" and block.get("is_error"):
            unit["error_count"] += 1
    if unit["lane"] == "lead" and not unit["lead_text"]:
        unit["lead_text"] = _first_text(turn)


def _unit_merge_penalty(left: dict, right: dict) -> tuple:
    lane_change = int(left["lane"] != right["lane"])
    anomaly = int(bool(left["error_count"]) != bool(right["error_count"]))
    keep_summary = int(left.get("is_summary") or right.get("is_summary"))
    return (keep_summary, lane_change, anomaly, left["turn_count"] + right["turn_count"])


def _merge_units(left: dict, right: dict) -> dict:
    out = dict(left)
    out["end_turn"] = right["end_turn"]
    out["last_ts"] = right["last_ts"]
    for field in ("turn_count", "tool_count", "error_count", "subagent_count"):
        out[field] = left[field] + right[field]
    out["tool_counts"] = left["tool_counts"] + right["tool_counts"]
    out["target"] = left["target"] or right["target"]
    out["is_summary"] = left.get("is_summary") or right.get("is_summary")
    # keep the dominant lane by combined tool evidence, else the left lane
    if left["lane"] != right["lane"]:
        pick = Counter()
        pick[left["lane"]] += left["tool_count"] + (1 if left["lane"] == "lead" else 0)
        pick[right["lane"]] += right["tool_count"] + (1 if right["lane"] == "lead" else 0)
        out["lane"] = max(pick, key=lambda l: (pick[l], -_UNIT_LANE_PRIORITY.get(l, 9)))
    return out


def _compact_units(units: list[dict], max_units: int) -> list[dict]:
    groups = list(units)
    while len(groups) > max_units:
        index = min(range(len(groups) - 1),
                    key=lambda i: (_unit_merge_penalty(groups[i], groups[i + 1]), i))
        groups[index:index + 2] = [_merge_units(groups[index], groups[index + 1])]
    return groups


def _finalize_units(units: list[dict], max_units: int) -> list[dict]:
    if not units:
        return []
    # The clearance ENDS at the agent's closing summary: if the last unit is a
    # text-only assistant turn (lane lead, no tools), promote it to a Gate
    # handoff so every route terminates on a decision node.
    last = units[-1]
    if last["lane"] == "lead" and last["tool_count"] == 0 and last is not units[0]:
        last["lane"] = "gate"
        last["is_summary"] = True
        last["lead_text"] = last.get("lead_text") or "Handoff"
    compacted = _compact_units(units, max_units)
    out = []
    for i, unit in enumerate(compacted):
        top_tools = [{"name": n, "count": c} for n, c in unit["tool_counts"].most_common(4)]
        out.append({
            "id": f"u{i}-{unit['start_turn']}-{unit['end_turn']}",
            "sequence": i + 1,
            "lane": unit["lane"],
            "label": _unit_label(unit),
            "is_summary": unit["is_summary"],
            "start_turn": unit["start_turn"],
            "end_turn": unit["end_turn"],
            "turn_count": unit["turn_count"],
            "tool_count": unit["tool_count"],
            "error_count": unit["error_count"],
            "subagent_count": unit["subagent_count"],
            "first_ts": unit["first_ts"],
            "last_ts": unit["last_ts"],
            "top_tools": top_tools,
        })
    return out


def build_clearance_routes(path: str, max_units: int = DEFAULT_MAX_UNITS) -> dict:
    """Stream a session and return one role-lane route per user instruction."""
    max_units = max(MIN_UNITS, min(int(max_units), MAX_UNITS))
    title = project = first_ts = last_ts = None
    title_priority = 0
    total_turns = 0
    clearances: list[dict] = []
    current = None          # current clearance dict
    current_units = None    # list[unit] for the current clearance
    current_unit = None

    def close_clearance():
        if current is not None:
            current["units"] = _finalize_units(current_units, max_units)

    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            typ = obj.get("type")
            if typ == "custom-title" and obj.get("customTitle"):
                title, title_priority = obj["customTitle"], 3
            elif typ == "ai-title" and obj.get("aiTitle") and title_priority < 2:
                title, title_priority = obj["aiTitle"], 2
            elif typ == "summary" and obj.get("summary") and title_priority < 1:
                title, title_priority = obj["summary"], 1
            if typ not in ("user", "assistant"):
                continue
            turn = transcript._norm_turn(obj)
            if turn is None:
                continue
            total_turns += 1
            project = project or obj.get("cwd")
            ts = turn.get("ts")
            if ts:
                first_ts = first_ts or ts
                last_ts = ts

            prompt = _instruction_text(turn)
            if prompt:
                close_clearance()
                current = {
                    "index": len(clearances),
                    "label": _clean_text(prompt, 160),
                    "first_prompt": _clean_text(prompt),
                    "start_turn": total_turns,
                    "first_ts": ts,
                }
                clearances.append(current)
                current_units = []
                # seed the Lead unit with the instruction itself
                current_unit = _new_unit("lead", total_turns, turn)
                current_unit["lead_text"] = prompt
                current_units.append(current_unit)
                _absorb_turn(current_unit, total_turns, turn)
                continue

            if current is None:
                current = {
                    "index": 0, "label": "Session setup", "first_prompt": "Session setup",
                    "start_turn": total_turns, "first_ts": ts,
                }
                clearances.append(current)
                current_units = []
                current_unit = _new_unit("lead", total_turns, turn)
                current_units.append(current_unit)

            # A non-instruction USER turn is a tool result or injected wrapper:
            # it belongs to whatever the agent was doing, so it stays in the
            # current unit and never starts a spurious "lead" unit between two
            # runs of the same work.
            if turn.get("role") == "user":
                lane = current_unit["lane"] if current_unit else "lead"
            else:
                lane = _turn_lane(turn)
            if current_unit is None or lane != current_unit["lane"]:
                current_unit = _new_unit(lane, total_turns, turn)
                current_units.append(current_unit)
            _absorb_turn(current_unit, total_turns, turn)

    close_clearance()

    # summarize each clearance
    for c in clearances:
        units = c.get("units", [])
        c["end_turn"] = units[-1]["end_turn"] if units else c["start_turn"]
        c["last_ts"] = units[-1]["last_ts"] if units else c["first_ts"]
        c["turn_count"] = sum(u["turn_count"] for u in units)
        c["tool_count"] = sum(u["tool_count"] for u in units)
        c["error_count"] = sum(u["error_count"] for u in units)
        c["subagent_count"] = sum(u["subagent_count"] for u in units)
        c["unit_count"] = len(units)
        c["lane_counts"] = dict(Counter(u["lane"] for u in units))

    return {
        "title": title,
        "project": project,
        "first_ts": first_ts,
        "last_ts": last_ts,
        "rule_version": ROUTE_RULE_VERSION,
        "max_units": max_units,
        "source": {
            "turn_count": total_turns,
            "clearance_count": len(clearances),
        },
        "lanes": list(CLEARANCE_LANES),
        "clearances": clearances,
    }


def load_clearance_routes(projects_dir: str, session_id: str,
                          max_units: int = DEFAULT_MAX_UNITS) -> dict | None:
    path = transcript.find_session_file(projects_dir, session_id)
    if not path:
        return None
    data = build_clearance_routes(path, max_units=max_units)
    data["session_id"] = session_id
    return data


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a compact Route Loom projection")
    parser.add_argument("session_id")
    parser.add_argument("--projects-dir", default="~/.claude/projects")
    parser.add_argument("--max-waypoints", type=int, default=DEFAULT_MAX_WAYPOINTS)
    args = parser.parse_args()
    data = load_session_route(os.path.expanduser(args.projects_dir), args.session_id,
                              max_waypoints=args.max_waypoints)
    if data is None:
        parser.error("session not found")
    print(json.dumps(data, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
